name: artblender
description: "artblender_app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  screenshot: ^3.0.0
  image_picker: ^1.0.7
  camera: ^0.11.0
  path_provider: ^2.0.11 # 임시 파일 저장을 위해 추가
  image_gallery_saver_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
